### ISSUE TITLE
How to change a different structure, such as a bridge to do the simulation?

### ISSUE THREAD

**Issue by lida2003** [HKUST-Aerial-Robotics/FC-Planner#10]
Hi

I'm very interestind in 3D scene re-construction, I wanna know much more detaild info.

Now, I wanna know how to change a different object, such as a bridge, to do the simulation?

Thanks.

**Comment by Chen-Albert-FENG** [comment]
You can refer to this issue [how to use own dataset](https://github.com/HKUST-Aerial-Robotics/FC-Planner/issues/7). If you want to use your own data, you should carefully adjust the parameters following readme.

**Comment by lida2003** [comment]
It's more general. As a newbee to the area, I hope more info or links to the tools or step by step tutorials.

Maybe some related links to those concepts/tools will help.

Hope to see more in-depth readme on https://sysu-star.github.io/FC-Hetero/

**Comment by Chen-Albert-FENG** [comment]
> It's more general. As a newbee to the area, I hope more info or links to the tools or step by step tutorials.
> 
> Maybe some related links to those concepts/tools will help.
> 
> Hope to see more in-depth readme on https://sysu-star.github.io/FC-Hetero/

@lida2003 
1. I think the readme documentation is clear and you can change some parameters in the launch file for your own application.
![20240607-124520](https://github.com/HKUST-Aerial-Robotics/FC-Planner/assets/63229950/97bd75f3-c58e-4494-9f2b-910a3c39d244)
2. More specific tutorials? Please see https://github.com/HKUST-Aerial-Robotics/FC-Planner/blob/master/FC-Planner/src/rosa/README.md and https://github.com/HKUST-Aerial-Robotics/FC-Planner/blob/master/FC-Planner/src/viewpoint_manager/README.md. As for how to change input file, I think it's easy to find the corresponding parameters. 
3. Since [FC-Hetero](https://sysu-star.github.io/FC-Hetero/) is submitted to IROS2024, still under review, this project cannot be open-source now. Once accepted, we will release our code.

**Comment by lida2003** [comment]
@Chen-Albert-FENG Thanks for you kindly help and quick response. That's a startup point for me. Thanks again.
